server:
    port: ENC[AES256_GCM,data:mQvaAQ==,iv:Pw8fp9tLjgncA0z9WH1f1ApF6fnRtCe4P02wVI0lOAg=,tag:lAKaJXX2MSMQV4G29P/1AA==,type:int]
    env: ENC[AES256_GCM,data:Gzg9,iv:yS0qMcFHP+6/sRuAcoIPC+grAsR//2pxePPYOXu7EBM=,tag:uwTjNQTubv8+MyZ8dpms1w==,type:str]
database:
    base_url: ENC[AES256_GCM,data:xBeW7Coy9AJzs5i9x9JjL6Omy5AYR8oEg5S+lAffz64wjCwEYnIbOw==,iv:ybxN4pwvQJoG8izAhKB1jcJlNJ/YkDdEyt0OIs/NIhY=,tag:5387GWbmoqjgWAtaG437Bg==,type:str]
    key: ENC[AES256_GCM,data:MgQ2VL/6mfwwe6KslqolVddyprlY3AxFQfs9VZPxgcHzrYLHFTuVgRNQzozbabpGgIysqD3VclaDwOtgKwTuzHcaxD9OyLARyXgzy+Jrrp9wP60BhUaYf0Ck3BGOnlRZ5vwoWNsFoq/tyFz1GQGSg045fo4ygmcGZIgDxI1OaetS2qylHRLTrQJf5oR6oJibKiBW3ICDnyvJ8vZZ07HINLZL132uSmMXIqg0OPjquz4p0ws/IYzPcXuoDJmw6zrttgHbhi7v1yzyW2uPPTgspw==,iv:Lue+oCXWpb525wLBGLrKdYKj/qquFwkbmTtVWQwsmN4=,tag:Wfv3cIUCdevw+hxyhqnbug==,type:str]
github:
    token: ENC[AES256_GCM,data:EhVoZXSO8/bCNvgobHAh4nF5je3RB00mtfLLWz6n5QYDmNE67pLVLw==,iv:ISBHhwJ0S28VJFT0dSvfduZEzrvdkQWm7qUwhrEg/Iw=,tag:B2p/8f7mEwfX0sH8BjQG8w==,type:str]
summary_assistant:
    api_key: ENC[AES256_GCM,data:xRvsU2gnvSuP+pbKKUq+DTVeHdPZdk75iLj+ZUssB/qA+VW6+fZPGSWo9WZ1FugreWh1D/rgOqvI5X6yWSECguAqNZU/RyQvt1ADNPOobMPhbh0pXNTAXekHvE03lc0=,iv:cATsUt0wq9REFWXg6y32/abhWJay/0Y5gW8frBs2x54=,tag:pwIFPNkWPyaXpLSP+72/Sg==,type:str]
logging:
    level: info
cors:
    allow_origins: ENC[AES256_GCM,data:7EJi8r6ziaRorp8/T6Oh9KSC28xDl0vlQ9t4mkeZaibmhQqkvBPqeDfkeimwGRp16mcf,iv:zHgV/wR4ADIkWR1NQgiwbPvFa3NcxZCO2/KOzLdbCSg=,tag:tVUys5WM//gBqYYJt0g0aw==,type:str]
    allow_methods: ENC[AES256_GCM,data:iqoTxY5YI6PuPFZicvMqNBXD3OaSUA==,iv:oCUdaznJ4aCssLAV8PHiJqsR26XoGjRA6LxDcY1fWpA=,tag:DS3EAUXPhc/+jywxdLDXXg==,type:str]
    allow_headers: ENC[AES256_GCM,data:696dcM5uOxpJ6KITavMcfJUhJrR0eynU2o0=,iv:RzBMgLXiEc8cb9p+wJks2OF0ruToQ0Wk8IKsPGXjLi0=,tag:M4HbkKAqM0Ets8RWSgBKxA==,type:str]
    allow_credentials: ENC[AES256_GCM,data:Gd3rPg==,iv:KNj0aUEVSrqJgcveDHNQokOmbRTcP4aebZj448vj/Kw=,tag:aHrATZV+yefj9LF0arTiAA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xs3094qjr954kqcqpy02unxpjpq9m8fgvsmurevkqxmsxc9z7dmq52z4jt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNDFObjdMZ1NDc2U1QUpK
            NTM3aVk3c3ZKa1A0MFUvSXZBbkMrOFNnZHlrCnpTN0FMbXJXdmxxSEFFSVpnWjBt
            K20rOWlvZUtIaW1WRTJEN3VEd1h2ajAKLS0tIEd6OGsvckI0ZUJVL3hzSGo4RkNI
            dnV0bTdiN3RSWXREZDhKZ2toNDY2c1UKFRIbNGpZoapLFpouRGrqpFZhdnCRgi12
            3tF6nEhKladmv3swQ1V2Gd0MwUVdscGQ7m3qIuCB4yZcghcEzbH5lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T08:55:46Z"
    mac: ENC[AES256_GCM,data:b2DWktLK8Tf3E6FWEECV2I60iYVIrPBPO8rD53NInl8/32HktaD+k34RdSn7AHG3JcAPNKZvqCD8bETQIruoSe+6f7o45k+0sWd+xRlAIqQRzGVc1Xbeog6FzxW/1vHdFJhM5VxdyBUKx4GFqdsqTrAsjYzatZKFq3EgLZOlvQc=,iv:RscvzVRlr+2zPPGe3deWtxum384aVf/1d6VrphhZXqw=,tag:QBEHu3I2TTiAGBZgebVZVA==,type:str]
    pgp: []
    unencrypted_regex: ^(logging)$
    version: 3.9.3
